// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Microsoft.Azure.PowerShell.Ssh.Helpers.Network.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Response for GetActiveSessions.
    /// </summary>
    public partial class BastionActiveSessionListResult
    {
        /// <summary>
        /// Initializes a new instance of the BastionActiveSessionListResult
        /// class.
        /// </summary>
        public BastionActiveSessionListResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BastionActiveSessionListResult
        /// class.
        /// </summary>
        /// <param name="value">List of active sessions on the bastion.</param>
        /// <param name="nextLink">The URL to get the next set of
        /// results.</param>
        public BastionActiveSessionListResult(IList<BastionActiveSession> value = default(IList<BastionActiveSession>), string nextLink = default(string))
        {
            Value = value;
            NextLink = nextLink;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets list of active sessions on the bastion.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<BastionActiveSession> Value { get; set; }

        /// <summary>
        /// Gets or sets the URL to get the next set of results.
        /// </summary>
        [JsonProperty(PropertyName = "nextLink")]
        public string NextLink { get; set; }

    }
}
